fname=inputbox ("komichiwa")
fname=inputbox ("i am ASUNA")
fname=inputbox ("whats your name")
fname=inputbox ("thats a good name")
fname=inputbox ("do you like anime or manga?")
fname=inputbox ("thats cool")
fname=inputbox ("pi=3.14")
fname=inputbox ("4*8=?")
fname=inputbox ("32")
fname=inputbox ("my creator is IBRAHIM MIRZA a.k.a shah programmer")
fname=inputbox ("what is the capital of RUSSIA")
fname=inputbox ("MOSCOW")
fname=inputbox ("what is BERLIN")
fname=inputbox ("the capital of GERMANY")
fname=inputbox (" i^5=?")
fname=inputbox ("i")
fname=inputbox ("what is your favorite anime?")
fname=inputbox ("cool!!")
fname=inputbox ("what is your favorite manga")
fname=inputbox ("nice")
fname=inputbox ("whats my favorite anime and manga you ask?")
fname=inputbox ("NEGIMA,HOTD,SE,UQ HOLDER")
fname=inputbox ("well im going on break :")
fname=inputbox ("slopeintercept= y=mx+b")
fname=inputbox ("101001010101010")
fname=inputbox ("well bye")
